### PR TITLE
Stop adding empty lines to spec files

### PR DESCRIPTION
**Pull request by Lex-2008**
Also Add build-tagging feature to cf-bottom

----

#

### CODE REVIEW

**Review by vpodzime — COMMENTED** [review]
The second commit looks incomplete.

**Comment by Lex-2008** [comment]
right, it's a follow-up to https://github.com/cf-bottom/self/pull/54 which adds this feature, but doesn't enable it

**Review by vpodzime — APPROVED** [review]
ACK

**Review by cf-bottom — APPROVED** [review]
I trust @vpodzime, approved!

**Pull request merged**
