### PR TITLE
Fix detection of postgresql version

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @olehermanse can review this?

**Comment by Lex-2008** [comment]
Buildscript PR created after this change: https://github.com/cfengine/buildscripts/pull/573

**Comment by Lex-2008** [comment]
Ok, but will we be able to backport that fix to 3.12.x branch?

**Comment by vpodzime** [comment]
> Ok, but will we be able to backport that fix to 3.12.x branch?

Why not? It's just a change of name of one folder and maybe some files in buildscripts, nothing affecting the packages we build, right?

**Comment by Lex-2008** [comment]
right

**Pull request closed without merging**
