### PR TITLE
Replaced all occurences of cf-bottom with a variable

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @vpodzime can review this?

**Comment by oleorhagen** [comment]
like `tom.username?` package variable?

**Comment by olehermanse** [comment]
Let's not.

**Comment by olehermanse** [comment]
@oleorhagen please rebase on latest master, then this can be merged.

**Comment by oleorhagen** [comment]
@olehermanse Done!

**Pull request merged**
